const path = require('path');
const webpack = require('webpack');
const { merge } = require('webpack-merge');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const commonConfig = require('./webpack.common.js');

module.exports = merge(commonConfig, {
  // debug: true, //TODO: figure out what this means
  mode: 'development',
  output: {
    path: path.resolve(__dirname, './build'),

    // Public this would affect the script tags
    // generated by HtmlWebpackPlugin
    // file paths will be prefixed by the path defined here
    // it should be the designated path for static assets
    publicPath: '/',

    filename: '[name].js',
  },
  plugins: [
    new MiniCssExtractPlugin()
  ],
  devtool: 'cheap-module-source-map',
  devServer: {

    // this is the endpoint where the webpack static/bundle assets
    // will be served, by default it's '/'
    host: '0.0.0.0',
    port: 8089,
    // contentBase: 'build',
    historyApiFallback: true,
    headers: { 'Access-Control-Allow-Origin': '*' },
    devMiddleware: {
      stats: 'minimal',
      publicPath: '/'
    }
  }
});
