export const INCOMING_MESSAGE_PAYLOAD = 'INCOMING_MESSAGE_PAYLOAD';

export const ADD_MESSAGE = 'ADD_MESSAGE';

export const START_CHANNEL = 'START_CHANNEL';
export const STOP_CHANNEL = 'STOP_CHANNEL';
export const CHANNEL_ON = 'CHANNEL_ON';
export const CHANNEL_OFF = 'CHANNEL_OFF';
export const SERVER_ON = 'SERVER_ON';
export const SERVER_OFF = 'SERVER_OFF';

export const SEND_MESSAGE = 'SEND_MESSAGE';

export const UPDATE_NUM_OF_USERS = 'UPDATE_NUM_OF_USERS';
